services:
  motion_planner:
    image: motion_planner:latest
    container_name: motion_planner
    working_dir: /app
    build: ./motion_planner
    volumes:
      - .:/app                    # Mount entire folder
      - /tmp/.X11-unix:/tmp/.X11-unix
    command : python3 /app/planner.py
    environment:
      - PYTHONPATH=/usr/local/lib/python3.10/dist-packages
      - DISPLAY=${DISPLAY}
    # Deploy on GPU if available
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             count: 1
             capabilities: [gpu]
    networks:
      - bridge_internet

networks:
  default:
    driver: macvlan
    driver_opts:
      parent: enp8s0  
    ipam:
      config:
        - subnet: 192.168.20.0/24 # 192.168.20.0 to 192.168.20.255
  bridge_internet:
    driver: bridge
